version: '3'

tasks:
  cuvanity:
    cmds:
      - docker run --rm -it --gpus=all ghcr.io/neodyland/cuvanity {{.CLI_ARGS}} | tee -a keys.txt
  cuvanity-gen:
    cmds:
      - docker run --rm -it -v ./keys.txt:/work/keys.txt -v ./build:/work/build ghcr.io/neodyland/cuvanity-gen keys.txt
  routor:
    cmds:
      - docker run --rm -it --network host -e ADDR={{.CLI_ARGS}} -v ./build/$(ls -1 ./build | head -n 1)/:/work/hidden_service ghcr.io/neodyland/routor
  clean:
    cmds:
      - rm -rf build
      - rm keys.txt