name: Build and Push Docker Images

on:
  push:

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - file: ./cuvanity-gen/Dockerfile
            tag: ghcr.io/neodyland/cuvanity-gen:latest
            context: .
            runs-on: ubuntu-latest
          - file: ./cuvanity/Dockerfile
            tag: ghcr.io/neodyland/cuvanity:latest
            context: .
            runs-on: ubuntu-latest
          - file: ./routor/Dockerfile
            tag: ghcr.io/neodyland/routor:latest-arm64
            context: ./routor
            runs-on: ubuntu-latest
          - file: ./routor/Dockerfile
            tag: ghcr.io/neodyland/routor:latest-amd64
            context: ./routor
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          tags: ${{ matrix.tag }}
          push: true

  docker-merge:
    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Merge
        run: |
          docker buildx imagetools create -t ghcr.io/neodyland/routor:latest \
              ghcr.io/neodyland/routor:latest-amd64 \
              ghcr.io/neodyland/routor:latest-arm64